# Generated by Django 4.2.6 on 2023-10-31 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='courses', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(verbose_name='Duración (meses)'),
        ),
    ]
