# Generated by Django 4.2.6 on 2023-11-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=150, verbose_name='Horas totales'),
            preserve_default=False,
        ),
    ]
